# Generated by Django 6.0.6 on 2026-06-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('raw_data', models.JSONField(null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
    ]
